POST http://localhost:8080/postPrintedProduct
Content-Type: application/json

{
  "theme": "Theme",
  "publication": "Publication3",
  "typeOfProduct": "BOOK",
  "author": "Author3",
  "date": "2030-03-21"
}

